nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: BileMo
            description: Your gateway to BileMo's luxury smartphone collection !
            version: 2.0.0
        paths:
            /api/login:
                post:
                    operationId: loginUser
                    tags:
                        - Login Check
                    summary: Login user and obtain JWT token
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: "#/components/schemas/Credentials"
                    responses:
                        "200":
                            description: Returns the JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: "#/components/schemas/Token"
                        "401":
                            description: Invalid credentials
            /api/products:
                get:
                    tags: ["Bilemo Premium Phones"]
                    summary: Get all Bilemo smartphones
                    parameters:
                        - name: page
                          in: query
                          description: "La page que vous souhaitez récupérer"
                          required: false
                          schema:
                              type: integer
                              default: 1
                        - name: limit
                          in: query
                          description: "Le nombre d'éléments à afficher par page"
                          required: false
                          schema:
                              type: integer
                              default: 10
                    responses:
                        "200":
                            description: Returns all products
                            content:
                                application/vnd.bilemo.v1+json:
                                    schema:
                                        type: object
                                        properties:
                                            data:
                                                type: array
                                                items:
                                                    $ref: "#/components/schemas/Product"
                                            pagination:
                                                type: object
                                                properties:
                                                    total_items:
                                                        type: integer
                                                        example: 100
                                                    current_page:
                                                        type: integer
                                                        example: 1
                                                    total_pages:
                                                        type: integer
                                                        example: 10
                                                    limit:
                                                        type: integer
                                                        example: 10
                                application/vnd.bilemo.v2+json:
                                    schema:
                                        type: object
                                        properties:
                                            data:
                                                type: array
                                                items:
                                                    $ref: "#/components/schemas/ProductV2"
                                            pagination:
                                                type: object
                                                properties:
                                                    total_items:
                                                        type: integer
                                                        example: 100
                                                    current_page:
                                                        type: integer
                                                        example: 1
                                                    total_pages:
                                                        type: integer
                                                        example: 10
                                                    limit:
                                                        type: integer
                                                        example: 10
                        "400":
                            description: "Bad request, invalid pagination parameters"
            /api/products/{id}:
                get:
                    tags: ["Bilemo Premium Phones"]
                    summary: Get a specific product by its ID
                    parameters:
                        - in: path
                          name: id
                          required: true
                          schema:
                              type: integer
                    responses:
                        "200":
                            description: Returns the details of a specific product
                            content:
                                application/vnd.bilemo.v1+json:
                                    schema:
                                        $ref: "#/components/schemas/Product"
                                application/vnd.bilemo.v2+json:
                                    schema:
                                        $ref: "#/components/schemas/ProductV2"
            /api/customers:
                get:
                    tags: ["Client Administration"]
                    summary: Retrieve all your clients
                post:
                    tags: ["Client Administration"]
                    summary: Add a new client
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: "#/components/schemas/Customer"
                    responses:
                        "201":
                            description: Customer created
                            content:
                                application/json:
                                    schema:
                                        $ref: "#/components/schemas/Customer"
                        "400":
                            description: Invalid input data
            /api/customers/{id}:
                get:
                    tags: ["Client Administration"]
                    summary: Retrieve a specific client by their ID
                delete:
                    tags: ["Client Administration"]
                    summary: Delete a specific customer by their ID
                    parameters:
                        - in: path
                          name: id
                          required: true
                          schema:
                              type: integer
                              description: ID of the customer to delete
                    responses:
                        "204":
                            description: Customer deleted successfully, no content returned
                        "404":
                            description: Customer not found
                        "403":
                            description: Forbidden, the user is not allowed to delete this customer
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Customer:
                    type: object
                    properties:
                        id:
                            type: integer
                            readOnly: true
                            example: 1
                        name:
                            type: string
                            example: "Doe"
                        firstName:
                            type: string
                            example: "John"
                        email:
                            type: string
                            example: "johndoe@example.com"
                        phoneNumber:
                            type: string
                            example: "+1234567890"
                        address:
                            type: string
                            example: "123 Main St, Some City, Some Country"
                Product:
                    type: object
                    properties:
                        id:
                            type: integer
                            readOnly: true
                            example: 1
                        name:
                            type: string
                            example: "iPhone 18"
                        description:
                            type: string
                            example: "Latest model of iPhone with advanced features"
                        brand:
                            type: string
                            example: "Apple"
                ProductV2:
                    type: object
                    properties:
                        id:
                            type: integer
                            example: 1
                        name:
                            type: string
                            example: "iPhone 18"
                        description:
                            type: string
                            example: "Latest model of iPhone with advanced features"
                        brand:
                            type: string
                            example: "Apple"
                        comment:
                            type: string
                            example: "Newly added field for version 2"
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: "test@example.com"
                        password:
                            type: string
                            default: "password"
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
    areas:
        path_patterns:
            - ^/api(?!/login_check$)(?!/doc$) # Accepts routes under /api except /api/doc
