nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: BileMo
            description: Your gateway to BileMo's luxury smartphone collection !
            version: 2.0.0
        paths:
            /api/login:
                post:
                    operationId: loginUser
                    tags:
                        - Authentification
                    summary: Login user and obtain JWT token
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: "#/components/schemas/Credentials"
                    responses:
                        "200":
                            description: Returns the JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: "#/components/schemas/Token"
                        "401":
                            description: Invalid credentials
            /api/products:
                get:
                    tags: ["Bilemo Premium Phones"]
                    summary: Get all Bilemo smartphones
                    responses:
                        "200":
                            description: Returns all products
                            content:
                                application/vnd.bilemo.v1+json:
                                    schema:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/Product"
                                application/vnd.bilemo.v2+json:
                                    schema:
                                        type: array
                                        items:
                                            $ref: "#/components/schemas/ProductV2"
            /api/products/{id}:
                get:
                    tags: ["Bilemo Premium Phones"]
                    summary: Get a specific product by its ID
                    parameters:
                        - in: path
                          name: id
                          required: true
                          schema:
                              type: integer
                    responses:
                        "200":
                            description: Returns the details of a specific product
                            content:
                                application/vnd.bilemo.v1+json:
                                    schema:
                                        $ref: "#/components/schemas/Product"
                                application/vnd.bilemo.v2+json:
                                    schema:
                                        $ref: "#/components/schemas/ProductV2"
            /api/customers:
                get:
                    tags: ["Client Administration"]
                    summary: Retrieve all clients
                post:
                    tags: ["Client Administration"]
                    summary: Add a new customer
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: "#/components/schemas/Customer"
                    responses:
                        "201":
                            description: Customer created
                            content:
                                application/json:
                                    schema:
                                        $ref: "#/components/schemas/Customer"
                        "400":
                            description: Invalid input data
            /api/customers/{id}:
                get:
                    tags: ["Client Administration"]
                    summary: Retrieve a specific client by their ID
                delete:
                    tags: ["Client Administration"]
                    summary: Delete a specific customer by their ID
                    parameters:
                        - in: path
                          name: id
                          required: true
                          schema:
                            type: integer
                            description: ID of the customer to delete
                    responses:
                        "204":
                            description: Customer deleted successfully, no content returned
                        "404":
                            description: Customer not found
                        "403":
                            description: Forbidden, the user is not allowed to delete this customer
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Customer:
                    type: object
                    properties:
                        id:
                            type: integer
                            readOnly: true
                            example: 1
                        name:
                            type: string
                            example: "Doe"
                        firstName:
                            type: string
                            example: "John"
                        email:
                            type: string
                            example: "johndoe@example.com"
                        phoneNumber:
                            type: string
                            example: "+1234567890"
                        address:
                            type: string
                            example: "123 Main St, Some City, Some Country"
                Product:
                    type: object
                    properties:
                        id:
                            type: integer
                            readOnly: true
                            example: 1
                        name:
                            type: string
                            example: "iPhone 18"
                        description:
                            type: string
                            example: "Latest model of iPhone with advanced features"
                        brand:
                            type: string
                            example: "Apple"
                ProductV2:
                    type: object
                    properties:
                        id:
                            type: integer
                            example: 1
                        name:
                            type: string
                            example: "iPhone 18"
                        description:
                            type: string
                            example: "Latest model of iPhone with advanced features"
                        brand:
                            type: string
                            example: "Apple"
                        comment:
                            type: string
                            example: "Newly added field for version 2"
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: "test@example.com"
                        password:
                            type: string
                            default: "password"
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
     
     
